# Generated by Django 3.1 on 2020-08-25 17:05

import datetime

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tweet",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        default=datetime.datetime.utcnow, editable=False
                    ),
                ),
                ("content", models.TextField()),
            ],
        ),
    ]
