# Generated by Django 3.1 on 2020-08-29 09:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(name="tweet", options={"ordering": ["-created"]},),
    ]
