# Generated by Django 3.1.1 on 2020-09-06 19:55

import uuid

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Campaign",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("enabled", models.BooleanField(default=False)),
                ("active_from", models.DateTimeField(blank=True, null=True)),
                ("active_till", models.DateTimeField(blank=True, null=True)),
                ("name", models.TextField()),
                ("celebrity", models.TextField()),
                ("social_platform", models.TextField(blank=True, null=True)),
                ("social_url", models.URLField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Photo",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField()),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="pr.campaign",
                    ),
                ),
            ],
        ),
    ]
