# Generated by Django 3.1.1 on 2020-09-30 03:45

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Gamer",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("chat_id", models.TextField(unique=True)),
                ("high", models.IntegerField(blank=True, null=True)),
                (
                    "money",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=26, null=True
                    ),
                ),
                ("need_new_high", models.BooleanField(default=False)),
            ],
        ),
    ]
