# Generated by Django 3.0.8 on 2020-08-04 18:45

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="visible",
            field=models.BooleanField(default=False),
        ),
    ]
