# Generated by Django 3.1 on 2020-08-22 08:49

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_project_visible"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="search_name",
            field=models.TextField(blank=True, editable=False, null=True),
        ),
    ]
