# Generated by Django 3.0.8 on 2020-08-01 10:58

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Visit",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("at", models.DateTimeField()),
                ("cl", models.PositiveIntegerField()),
                ("code", models.PositiveIntegerField()),
                ("method", models.TextField()),
                ("tm", models.FloatField()),
                ("url", models.URLField()),
            ],
        ),
    ]
