# Generated by Django 3.0.8 on 2020-08-04 18:28

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("stats", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="visit",
            name="at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="visit",
            name="cl",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="visit",
            name="code",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="visit",
            name="method",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="visit",
            name="tm",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="visit",
            name="url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
