# Generated by Django 3.1.1 on 2020-09-02 07:41

import django.db.models.deletion
import storages.backends.s3boto3
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("onboarding", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Avatar",
            fields=[
                (
                    "profile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="onboarding.profile",
                    ),
                ),
                (
                    "original",
                    models.FileField(
                        storage=storages.backends.s3boto3.S3Boto3Storage(),
                        upload_to="avatars",
                    ),
                ),
            ],
        ),
        migrations.RemoveField(model_name="profile", name="id",),
        migrations.AlterField(
            model_name="profile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                serialize=False,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
