# Generated by Django 3.1.1 on 2020-09-05 09:48

import storages.backends.s3boto3
from django.db import migrations
from django.db import models

import applications.onboarding.models.avatar


class Migration(migrations.Migration):
    dependencies = [
        ("onboarding", "0002_auto_20200902_0741"),
    ]

    operations = [
        migrations.AlterField(
            model_name="avatar",
            name="original",
            field=models.FileField(
                storage=storages.backends.s3boto3.S3Boto3Storage(),
                upload_to=applications.onboarding.models.avatar.upload_to,
            ),
        ),
    ]
